### ISSUE TITLE
Package and classes error

### ISSUE THREAD

**Issue by Prasanna20596** [opencrx/opencrx#122]
Hi, If i clone the project in my local, project is fully error occurred. So what can i do?
![Screenshot from 2023-05-16 19-19-13](https://github.com/opencrx/opencrx/assets/115647245/8f68ecae-13db-452d-82c9-949b844072bc)

**Comment by javac9** [comment]
Try running
`gradle clean assembly eclipse` and then re-import the project into Eclipse IDE
