### ISSUE TITLE
Support for 2FA with TOTP

### ISSUE THREAD

**Issue by wfro64** [opencrx/opencrx#133]
Support for Two-Factor Authentication with Time-based One-Time Passwords (TOTP)

**Comment by fschon** [comment]
Maybe also support OpenID login?

**Comment by wfro64** [comment]
Activate 2FA by launching the wizard Home > Security > Create TOTP

![Screenshot_20231111_105647](https://github.com/opencrx/opencrx/assets/11387061/e91e8a47-658a-4dd3-8de6-7e9e3e27dd85)

The wizard shows the secret key, account name and issuer. Change if required the click OK.

![Screenshot_20231111_105714](https://github.com/opencrx/opencrx/assets/11387061/9cb2282c-6a20-4d5e-82f6-8dfa848325a2)

This generates a QR code and stores the secret key, account name and issuer as media attachement with name TOTP.

![Screenshot_20231111_105733](https://github.com/opencrx/opencrx/assets/11387061/cb7150e9-ea25-4dbc-9745-252293584e22)

![Screenshot_20231111_110019](https://github.com/opencrx/opencrx/assets/11387061/8efa56fb-9076-4e57-b145-7fbca726e3b5)

Scan the QR code with any TOTP app (e.g. Google Authenticator, FreeOTP).

Login now requires a valid TOTP authentication

![Screenshot_20231111_105904](https://github.com/opencrx/opencrx/assets/11387061/9b6feb46-ed24-47b8-802e-f8b981565fc3)

NOTE:
- 2FA must be activated for each segment
- 2FA authentication is deactivated by removing the TOTP media

**Comment by wfro64** [comment]
OpenID can be implemented by fronting TomEE with httpd, nginx, iis, ... and delegate with AJP to TomEE. Also see https://github.com/openmdx/openmdx/blob/master/tomcat/src/main/java/org/openmdx/catalina/authenticator/RemoteUserAuthenticator.java
