### ISSUE TITLE
Attribute `aliasName` is defined as `String` type but an `int` value will be shown as `ìnt` in REST

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx#135]
I just noticed that some records in demo opencrx return value of `aliasName` as `String` while others return it as `int`

int (id: `L06YVSZTGFSHACZPUSCQKLY7Q` or `0757f70f-847f-11e0-98e5-1bd1e8c9a31d`)
![image](https://github.com/opencrx/opencrx/assets/25393309/47836fe3-187b-4c36-aad3-00c118d6c6ce)

String (id: `2R8GEzbYEd6dnikL5FGtGw`)
![image](https://github.com/opencrx/opencrx/assets/25393309/257e07ed-a32b-4c06-86a4-396f60740bb7)

**Comment by wfro64** [comment]
Rendering is value-based. openCRX uses org.openmdx.application.rest.http.servlet.RestServlet_2 which renders the output using org.openmdx.base.rest.stream.StandardRestFormatter. StandardRestFormatter does not propagate attribute-level type-information to the underlying XMLStreamWriter. As a result org.openmdx.base.json.stream.StandardXMLStreamWriter is unable to determine the modeled type of "aliasName" and render it as "34234324". 

Fixing this would be an openMDX feature request.
