### ISSUE TITLE
Error in console on server start: java.lang.OutOfMemoryError: Java heap space [Windows 10]

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx#43]
Version: 4.3.0-rc.1

Error in console on server start: java.lang.OutOfMemoryError: Java heap space

I tried changing the following in the `db.bat` file (note the port was also changed from `9001` to `9003`):

`cd C:\Users\dkaj\__TOOLS__\OpenCRX\SERVER\opencrxServer-4.3.0-rc.1\data\hsqldb
java -Xmx800M -cp .\hsqldb.jar org.hsqldb.server.Server --port 9003 --acl acl.txt --database.0 file:crx --dbname.0 CRX`

to

`cd C:\Users\dkaj\__TOOLS__\OpenCRX\SERVER\opencrxServer-4.3.0-rc.1\data\hsqldb
java -Xms3G -Xmx4G -cp .\hsqldb.jar org.hsqldb.server.Server --port 9003 --acl acl.txt --database.0 file:crx --dbname.0 CRX`

but no change.

**Comment by wfro64** [comment]
On several clean Windows 10 machines we did the following steps:

- download zulu8.46.0.19-ca-jdk8.0.252-win_x64.msi and install it in folder C:\opt
- download apache-ant-1.10.8-bin.zip and unzip to folder C:\opt
- download opencrxServer-4.3.0-rc.1-installer.jre-1.8.jar to C:\opt
- open command prompt
- set path to Zulu accordingly and verify with java -version
- cd C:\opt
- java -jar java -jar opencrxServer-4.3.0-rc.1-installer.jre-1.8.jar
- open command prompt
- cd C:\opt\opencrxServer-4.3.0-rc.1\data\hsqldb
- start db.bat run
- open command prompt
- cd C:\opt\opencrxServer-4.3.0-rc.1\apache-tomee-plus-7.0.5
- .\bin\catalina.bat run
- open browser in direct to http://127.0.0.1:8080/opencrx-core-CRX or http://127.0.0.1:9090/opencrx-core-CRX
- login as admin-Standard / admin-Standard
- create new objects, click in grids, etc. 
- no errors are reported on any console
![opencrx-v4 3 0-rc 1-runing-on-windows10](https://user-images.githubusercontent.com/11387061/86530658-b0f0ff80-beba-11ea-9b1b-c69f1fb3eaca.png)

**Comment by wfro64** [comment]
No feedback. wont' fix
