### ISSUE TITLE
[Docker on Windows 10] Cannot build the image

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx#45]
After successfully executing the pull command, I tried building the image but got the following error:

`C:\WINDOWS\system32>docker build -t opencrx:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Windows\System32\Dockerfile: The system cannot find the file specified.`

System: Windows 10 64-bit
Docker: Docker Desktop 2.3.0.3 (45519); Engine: 19.03.8
Active containers-setting: Linux containers

**Comment by wfro64** [comment]
If you have pulled the image from [here](https://hub.docker.com/r/opencrx/opencrx) you do not have to build the image again with `docker build ...`. Instead, run the image with `docker run ...` as described in the README.
