### ISSUE TITLE
opencrx-gradle Tasks are missing Input/Output annotations on Properties

### ISSUE THREAD

**Issue by brunoamacos** [opencrx/opencrx#51]
Some of the gradle tasks like ArchiveTask are missing an annotation on properties like providerName. 
Using these tasks in buildSrc is not possible because Task-Validation fails and build is stopped.

**Comment by wfro64** [comment]
Do you have a working example? E.g. for the ArchiveTask.

**Comment by brunoamacos** [comment]
This is my modified ArchiveTask
[AcoArchiveTask.kt.txt](https://github.com/opencrx/opencrx/files/4964745/AcoArchiveTask.kt.txt)

**Comment by wfro64** [comment]
Applying annotations as suggested results in compile errors:

        > Task :gradle:compileKotlin FAILED
        The `kotlin-dsl` plugin applied to project ':gradle' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.5.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (75, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (76, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (77, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (78, 3): Unresolved reference: OutputDirectory
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (79, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (80, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (81, 3): Unresolved reference: InputDirectory
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (82, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (83, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (84, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (85, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (86, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (87, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (88, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (89, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (90, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (91, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (92, 3): Unresolved reference: Internal
        e: ./opencrx/gradle/src/main/kotlin/org/opencrx/gradle/ArchiveTask.kt: (93, 3): Unresolved reference: Internal

**Comment by wfro64** [comment]
OK. `import org.gradle.api.tasks.Internal` was missing.
