### ISSUE TITLE
make archive tasks faster in development

### ISSUE THREAD

**Issue by brunoamacos** [opencrx/opencrx#52]
Archive tasks could be made faster if manifest generation is suppressed in development environments. This is because a changed manifest will trigger a rebuild of the archive file
Like
```java
		if (!project.hasProperty("developmentBuild")) {
		  manifest {
	             attributes(
	        	getManifest(
                                "openCRX/Core " + providerName + " WAR",
	        		"opencrx-core-" + providerName + ".war"	        	)
	             )
	         }
	       }
```
such local properties could be declared in ~/.gradle/gradle.properties

**Comment by wfro64** [comment]
How about to change ArchiveTask.getManifest() as follows?

EXISTING:
`"Implementation-Version" to projectImplementationVersion + "-" + buildTime()`

NEW:
`"Implementation-Version" to projectImplementationVersion`

Since the buildTime is not really required in "Implementation-Version".
