### ISSUE TITLE
ActivityGroup extends both Account and CrxObject while Account itself extends CrxObject

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx#63]
In the past I already wrote on SourceForge about this issue (context is ahead).

I once again encountered the issue (with another interface) but I know now what the issue is (and what was before).

Now it's about `LegalEntity`. My framework complains that `duplicate key for a property was found... etc.`.

I wondered how come simply using `cc2` over `jmi1` version worked for `Contact`s but it won't work for `LegalEntity`.

The reason is in the inheritance chain:

`public interface LegalEntity extends AbstractGroup` and  `public interface AbstractGroup extends Account, CrxObject`

Now, the real issue seems to be the `CrxObject` part since `Account extends CrxObject` as well. Vaadin complains about finding duplicate keys for property "Audit" -- `CrxObject extends Auditee` and these two parallel paths are the cause,  I suspect.

Does `AbstractGroup` really have to `extend CrxObject` since it already extends `Account` which itself already does that?

**Comment by javac9** [comment]
In the meantime, I'd like to share more details.

I've overridden the Vaadin `Binder` class so I should be able to manipulate the object in my class before invoking the `super` constructor.
```
public class MyBinder<L extends AbstractGroup> extends Binder<LegalEntity> {

    public MyBinder(Class<LegalEntity> beanType) {
        
        // here I hope I should be able to somehow remove the offending (or the extra interface CrxObject - provided it really is not necessary since it can be inferred implicitly from Account which extends CrxObject
       // the reason is: when inpecting the "beanType" object in my IDE, I noticed the following hierarchy:

       // beanType []
       //     reflectionData []
       //         referent []
       //             interfaces []
       //                 [0]:
       //                     name: "org.opencrx.kernel.account1.cci2.AbstractGroup"
       //                     reflectionData []
       //                         referent []
       //                             interfaces []
       //                                 [0]:
       //                                     name: "org.opencrx.kernel.account1.cci2.Account"
       //                                 [1]:
       //                                     name: "org.opencrx.kernel.generic.cci2.CrxObject"

        super(beanType);
    }
}
```

Now, if I'm not being terribly naive, the idea would be, by using reflection, to remove the second interfaces element (CrxObject). If that were successful, the manipulated `beanType` object would be passed to the original Vaadin `Binder` without having this "extra" interface and binding should work fine.

The real question here is: from your experience, is such a thing possible (remove one of the inherited interfaces via reflection or in some other way)?

**Comment by javac9** [comment]
Any feedback on this? I suppose there's a reason why `AbstractGroup` has to extend both `Account` **and** `CrxObject` but if it doesn't have to -- would it be possible to get the next minor 5.x.x release with this change?

**Comment by wfro64** [comment]
Remove inheritance "AbstractGroup > CrxObject" since this is redundant.
