### ISSUE TITLE
Case insensitive query

### ISSUE THREAD

**Issue by fschon** [opencrx/opencrx#69]
Is it possible to perform a case insensitive query. In my case I need to do a search for a realm with a all lowercase string. So for example I want to search for the realm 'Standard' with the text 'standard'. Some realms are CamelCased and so I cannot just ignore the first character.

```
RealmQuery realmQuery = (RealmQuery) pm.newQuery(Realm.class);
realmQuery.name().equalTo("standard");  <-- this needs to be a case insensitive search!
```

Thx for the help.

**Comment by brunoamacos** [comment]
Hi fschon

realmQuery.name().like("(?i)standard");

**Comment by fschon** [comment]
Thanks Bruno, works great. Do you know of any documentation for other this and other tricks?
